import fs from 'node:fs';
import path from 'node:path';

const aliasPattern = /^\{([^}]+)\}$/;

function readJson(filePath) {
  return JSON.parse(fs.readFileSync(filePath, 'utf8'));
}

function isToken(value) {
  return Boolean(
    value && typeof value === 'object' && !Array.isArray(value)
      && '$type' in value && '$value' in value,
  );
}

export function loadTokenBundle(rootDir) {
  const tokenDir = path.join(rootDir, 'design-system', 'tokens');
  return {
    core: readJson(path.join(tokenDir, 'core.json')),
    semantic: readJson(path.join(tokenDir, 'semantic.json')),
    components: readJson(path.join(tokenDir, 'components.json')),
  };
}

export function flattenTokens(node, prefix = []) {
  const tokens = new Map();
  for (const [key, value] of Object.entries(node)) {
    const tokenPath = [...prefix, key];
    if (isToken(value)) {
      tokens.set(tokenPath.join('.'), value);
    } else if (value && typeof value === 'object' && !Array.isArray(value)) {
      for (const [nestedPath, token] of flattenTokens(value, tokenPath)) {
        tokens.set(nestedPath, token);
      }
    }
  }
  return tokens;
}

function cssName(tokenPath) {
  const kebabPath = tokenPath
    .split('.')
    .map((segment) => segment.replace(/([a-z0-9])([A-Z])/g, '$1-$2').toLowerCase())
    .join('-');
  return `--et-${kebabPath}`;
}

function cssValue(value) {
  if (typeof value === 'string') {
    const match = value.match(aliasPattern);
    return match ? `var(${cssName(match[1])})` : value;
  }
  if (Array.isArray(value) && value.length === 4) {
    return `cubic-bezier(${value.join(', ')})`;
  }
  if (value && typeof value === 'object' && 'offsetX' in value) {
    return `${value.offsetX} ${value.offsetY} ${value.blur} ${value.spread} ${value.color}`;
  }
  return String(value);
}

function renderBlock(selector, entries) {
  const declarations = entries
    .sort(([left], [right]) => left.localeCompare(right))
    .map(([tokenPath, token]) => `  ${cssName(tokenPath)}: ${cssValue(token.$value)};`)
    .join('\n');
  return `${selector} {\n${declarations}\n}`;
}

export function buildCss(bundle) {
  const blocks = [
    '/* Generated by npm run tokens:build. Do not edit directly. */',
    renderBlock(':root', [...flattenTokens(bundle.core)]),
  ];

  for (const mode of ['parchment', 'aubergine']) {
    const entries = [
      ...flattenTokens(bundle.semantic[mode]),
      ...flattenTokens(bundle.components[mode]),
    ];
    blocks.push(renderBlock(`[data-et-surface="${mode}"]`, entries));
  }

  blocks.push(`@media (prefers-reduced-motion: reduce) {\n  :root {\n    --et-motion-duration-deliberate: 0ms;\n    --et-motion-duration-fast: 0ms;\n    --et-motion-duration-standard: 0ms;\n  }\n}`);
  return `${blocks.join('\n\n')}\n`;
}

export function createRegistry(bundle) {
  const registry = new Map(flattenTokens(bundle.core));
  for (const mode of ['parchment', 'aubergine']) {
    for (const layer of ['semantic', 'components']) {
      for (const [tokenPath, token] of flattenTokens(bundle[layer][mode])) {
        registry.set(`${mode}.${tokenPath}`, token);
      }
    }
  }
  return registry;
}

export function resolveValue(value, registry, stack = []) {
  if (typeof value !== 'string') return value;
  const match = value.match(aliasPattern);
  if (!match) return value;

  const requestedPath = match[1];
  const mode = stack[0];
  if (/^(parchment|aubergine)\./.test(requestedPath)) {
    throw new Error(`Mode-qualified alias is prohibited: ${value}; use an unqualified token path`);
  }
  const candidates = mode
    ? [`${mode}.${requestedPath}`, requestedPath]
    : [requestedPath];
  const resolvedPath = candidates.find((candidate) => registry.has(candidate));

  if (!resolvedPath) throw new Error(`Unresolved alias: ${value}`);
  if (stack.includes(resolvedPath)) {
    throw new Error(`Circular alias: ${[...stack, resolvedPath].join(' -> ')}`);
  }

  return resolveValue(
    registry.get(resolvedPath).$value,
    registry,
    [...stack, resolvedPath],
  );
}

function channelToLinear(channel) {
  const normalized = channel / 255;
  return normalized <= 0.04045
    ? normalized / 12.92
    : ((normalized + 0.055) / 1.055) ** 2.4;
}

export function relativeLuminance(hex) {
  const match = /^#([0-9a-f]{6})$/i.exec(hex);
  if (!match) throw new Error(`Expected six-digit hex color, received: ${hex}`);
  const channels = match[1].match(/.{2}/g).map((part) => Number.parseInt(part, 16));
  const [red, green, blue] = channels.map(channelToLinear);
  return 0.2126 * red + 0.7152 * green + 0.0722 * blue;
}

export function contrastRatio(foreground, background) {
  const lighter = Math.max(relativeLuminance(foreground), relativeLuminance(background));
  const darker = Math.min(relativeLuminance(foreground), relativeLuminance(background));
  return (lighter + 0.05) / (darker + 0.05);
}

function aliasesDirectionBand(value, registry, mode, signalColors, visited = []) {
  if (typeof value !== 'string') return false;
  const match = value.match(aliasPattern);
  if (!match) return signalColors.has(value.toLowerCase());

  const requestedPath = match[1];
  const candidates = mode
    ? [`${mode}.${requestedPath}`, requestedPath]
    : [requestedPath];
  const resolvedPath = candidates.find((candidate) => registry.has(candidate));

  if (!resolvedPath || visited.includes(resolvedPath)) return false;
  if (resolvedPath.startsWith('color.signal.')) return true;

  return aliasesDirectionBand(
    registry.get(resolvedPath).$value,
    registry,
    mode,
    signalColors,
    [...visited, resolvedPath],
  );
}

export function validateTokenBundle(bundle) {
  try {
    return validateBundle(bundle);
  } catch (error) {
    return [`Invalid token bundle: ${error.message}`];
  }
}

function validateBundle(bundle) {
  const errors = [];
  const registry = createRegistry(bundle);

  for (const [tokenPath, token] of registry) {
    try {
      const mode = tokenPath.startsWith('parchment.')
        ? 'parchment'
        : tokenPath.startsWith('aubergine.')
          ? 'aubergine'
          : undefined;
      resolveValue(token.$value, registry, mode ? [mode] : []);
    } catch (error) {
      errors.push(`${tokenPath}: ${error.message}`);
    }
  }

  for (const layer of ['semantic', 'components']) {
    const parchment = [...flattenTokens(bundle[layer].parchment).keys()].sort();
    const aubergine = [...flattenTokens(bundle[layer].aubergine).keys()].sort();
    if (JSON.stringify(parchment) !== JSON.stringify(aubergine)) {
      errors.push(`${layer}: Parchment and Aubergine paths differ`);
    }
  }

  const approvedDirectionBandPaths = new Set([
    'semantic.color.focus.ring',
    'components.direction-band.research.color',
    'components.direction-band.decide.color',
    'components.direction-band.design.color',
    'components.direction-band.ship.color',
  ]);
  const signalColors = new Set(
    [...registry].filter(([tokenPath]) => tokenPath.startsWith('color.signal.'))
      .map(([, token]) => String(token.$value).toLowerCase()),
  );
  for (const mode of ['parchment', 'aubergine']) {
    for (const layer of ['semantic', 'components']) {
      for (const [tokenPath, token] of flattenTokens(bundle[layer][mode])) {
        if (typeof token.$value !== 'string' || !aliasPattern.test(token.$value)) {
          errors.push(`${mode}.${tokenPath}: ${layer} tokens must use an alias`);
          continue;
        }
        const isApprovedDirectionBandColor = approvedDirectionBandPaths.has(`${layer}.${tokenPath}`);
        if (
          !isApprovedDirectionBandColor
          && aliasesDirectionBand(token.$value, registry, mode, signalColors)
        ) {
          errors.push(`${mode}.${tokenPath}: Direction Band alias is prohibited`);
        }
      }
    }
  }

  // Resolve and policy errors already identify invalid inputs; avoid reporting them again in contrast.
  if (errors.length > 0) return errors;

  const resolved = (mode, tokenPath) =>
    resolveValue(registry.get(`${mode}.${tokenPath}`).$value, registry, [mode]);
  for (const mode of ['parchment', 'aubergine']) {
    const canvas = resolved(mode, 'color.surface.canvas');
    for (const status of ['info', 'success', 'warning', 'danger']) {
      if (contrastRatio(resolved(mode, `color.status.${status}`), canvas) < 4.5) {
        errors.push(`${mode}.color.status.${status}: contrast is below 4.5:1`);
      }
    }
    for (const signal of ['research', 'decide', 'design', 'ship']) {
      if (contrastRatio(registry.get(`color.signal.${signal}`).$value, canvas) < 3) {
        errors.push(`${mode}.color.signal.${signal}: contrast is below 3:1`);
      }
    }
  }

  return errors;
}
